sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t chkbarlow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chkbarlow/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  environment: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-2-787294604074"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY